prod:
  image: vizzuality/download-dataset:1.1.0${STAGING}
  ports:
    - "4300"
  env_file:
    - prod.env
  dns: ${DNS_SERVER}
  command: start
  log_driver: "gelf"
  restart: always
  log_driver: "syslog"
  log_opt:
      syslog-address: ${SYSLOG_ADDRESS}
      tag: download-dataset${STAGING}
