develop:
  extends:
    file: base.yml
    service: base
  container_name: download-dataset-api-develop
  environment:
    NODE_ENV: dev
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:4300
    DEBUG: "*"
  command: develop
  volumes:
    - ./app:/opt/download-dataset/app
