prod:
  image: vizzuality/download-dataset:1.0.0${STAGING}
  ports:
    - "4300"
  env_file:
    - prod.env
  dns: ${DNS_SERVER}
  command: start
  log_driver: "gelf"
  restart: always
  log_opt:
    gelf-address: ${GELF_ADDRESS}
